### PR TITLE
Fixing default search for /etc/docker/certs.d by image library

### LINKED ISSUE #21: Error attempting to use container-diff w/ gcr.io.  Permission denied for /etc/docker/certs.d/gcr.io
I have public images hosted @ gcr.io that I am attempting to diff.  When trying to run container-diff, I get the following errors:

aprindle@aprindle:~/runtimes-common/src/github.com/GoogleCloudPlatform/container-diff$ ./container-diff gcr.io/k8s-minikube
/localkube-dind-image:v1.7.0 gcr.io/k8s-minikube/localkube-dind-image:v1.7.0-devshell
E0817 11:31:59.112045   98632 image_prep_utils.go:121] open /etc/docker/certs.d/gcr.io: permission denied
E0817 11:31:59.112369   98632 root.go:75] open /etc/docker/certs.d/gcr.io: permission denied

Running the command with sudo resolves the issue

### PR DESCRIPTION
**Pull request by cftorres**
* Cleaned up leftover methods from old Docker dependencies 
* Used @r2d4's suggestion for ways to get around /etc/docker/certs.d error with new Image library usage

fixes #21 
@nkubala @aaron-prindle

### CODE REVIEW

File: utils/image_prep_utils.go [hunk 1]
```diff
@@ -157,7 +162,11 @@ func (p CloudPrepper) getConfig() (ConfigSchema, error) {
 		return ConfigSchema{}, err
 	}
 
-	img, err := ref.NewImage(nil)
+	cwd, _ := os.Getwd()
+	ctx := &types.SystemContext{
+		DockerCertPath: cwd,
```
Comment (r2d4) [inline utils/image_prep_utils.go]: Only comment here is that it will fail if your PWD has any certs in it (which I found out the hard way.) I might change my PR to set this to the output of `ioutil.TempDir()` just to be safe.

**Comment by runcom** [comment]
Pretty sure we fixed this in containers/image latest master, could you try that?
