### PR TITLE
Set/unset write bit on unwriteable directories when unpacking tars

### LINKED ISSUE #168: Centos image issues in mac
Hello Guys,

I'm using `container-diff` in mac, with docker-for-mac. 
I mainly use the analyze feature, And It works fine with debian/ubuntu based images.
However with centos based images, I have to run `container-diff` with `sudo` to make it work. Is this expected.

centos 7 without sudo 

```
> container-diff-darwin-amd64 analyze daemon://centos:7 --type=rpm
Retrieving image centos:7 from source Local Daemon
ERRO[0008] Error creating file /var/folders/_q/9t32sq_d1sg5vfv91dw5t0940000gq/T/centos7296082428/root/.bash_logout open /var/folders/_q/9t32sq_d1sg5vfv91dw5t0940000gq/T/centos7296082428/root/.bash_logout: permission denied 
ERRO[0008] Failed to untar layer with error: open /var/folders/_q/9t32sq_d1sg5vfv91dw5t0940000gq/T/centos7296082428/root/.bash_logout: permission denied 
Retrieving analyses

-----RPM-----

Packages found in centos:7: None

```

centos 7 with sudo

```
> sudo container-diff-darwin-amd64 analyze daemon://centos:7 --type=rpm
Retrieving image centos:7 from source Local Daemon
Retrieving analyses

-----RPM-----

Packages found in centos:7:
NAME                                VERSION          SIZE
-acl                                2.2.51           196.4K
-audit-libs                         2.7.6            242.2K
-basesystem                         10.0             0
-bash                               4.2.46           3.5M
...
[snip]
...
```

ubuntu 16.04 without sudo 
```
> container-diff-darwin-amd64 analyze daemon://ubuntu:16.04
Retrieving image ubuntu:16.04 from source Local Daemon
Retrieving analyses

-----Apt-----

Packages found in ubuntu:16.04:
NAME                        VERSION                              SIZE
-adduser                    3.113 nmu3ubuntu4                    648K
-apt                        1.2.24                               3.3M
...
[snip]
...
```

centos image is from the docker library (iid : 3fa822599e10)

I'm running this on macbook (El capitan) on container-diff v0.6.1, with docker-for-mac.

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

> container-diff-darwin-amd64 version
v0.6.1

> docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

### PR DESCRIPTION
**Pull request by nkubala**
When unpacking image tars, sometimes we run into directories that were unwriteable in the image. The directories will get created by container-diff, but then any subsequent files being written to the directory will fail. To fix this, we set the world-writable bit on the directory when we create it, then defer resetting the permissions so we can write all of its contents.

Fixes #168

### CODE REVIEW

File: pkg/util/tar_utils.go [hunk 1]
```diff
@@ -68,6 +68,13 @@ func unpackTar(tr *tar.Reader, path string, whitelist []string) error {
 		// if its a dir and it doesn't exist create it
 		case tar.TypeDir:
 			if _, err := os.Stat(target); os.IsNotExist(err) {
+				if mode.Perm()&(1<<(uint(7))) == 0 {
+					logrus.Debugf("Write permission bit not set on %s by default; setting manually", target)
+					originalMode := mode
+					mode = mode | (1 << uint(7))
+					defer os.Chmod(target, originalMode)
```
Comment (aaron-prindle) [inline pkg/util/tar_utils.go]: Chmod can return an Error, might be worth not deferring it and handling the error

Comment (nkubala) [reply pkg/util/tar_utils.go]: good call

**Comment by nkubala** [comment]
Unfortunately this only partially solves this issue, because once we reset the permissions outside of the scope of the user we can't remove or modify any of the files, meaning that we can't properly clean up the image on the filesystem. Still, this is better than what we had before, so I changed the message to a warn. The only real way to fix this issue is by moving the unpacked image from disk to memory, which is well outside the scope of this PR.
